# Generated by Django 3.0.6 on 2020-05-30 19:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_site1home'),
    ]

    operations = [
        migrations.AddField(
            model_name='site1home',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
