# Generated by Django 3.0.6 on 2020-05-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_site1home_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site1home',
            name='body',
        ),
    ]
