# Generated by Django 3.0.6 on 2020-06-03 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site1', '0010_site1blogtree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site1BlogTree',
            new_name='Site1Tree',
        ),
    ]
