# Generated by Django 3.0.6 on 2020-06-04 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('site1', '0014_site1categoryindex_site1querytag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site1TagIndexPage',
            new_name='Site1TagQuery',
        ),
    ]
