# Generated by Django 3.0.6 on 2020-06-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site1', '0017_auto_20200610_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site1TagQuery',
        ),
    ]
