# Generated by Django 3.0.6 on 2020-08-24 05:03

from django.db import migrations
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('site1', '0023_site1htmlpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='site1htmlpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='site1.Site1Category'),
        ),
        migrations.AddField(
            model_name='site1htmlpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='site1.Site1Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
