# Generated by Django 3.0.6 on 2020-08-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0024_auto_20200824_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site1htmlpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='site1htmlpage',
            name='tags',
        ),
    ]
