# Generated by Django 3.0.6 on 2020-08-25 16:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0025_auto_20200824_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='site1home',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock())], blank=True, null=True),
        ),
    ]
