# Generated by Django 3.0.6 on 2020-08-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('site1', '0027_site1rawhtml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site1HtmlPage',
        ),
    ]
