# Generated by Django 3.0.6 on 2020-06-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0007_auto_20200602_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site2index',
            name='intro',
        ),
    ]
