# Generated by Django 3.0.6 on 2020-06-02 10:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0008_remove_site2index_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='site2index',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
