# Generated by Django 3.0.6 on 2020-06-04 12:11

from django.conf import settings
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('site2', '0010_site2categoryindex_site2search_site2tagindex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site2CategoryIndex',
            new_name='Site2QueryCategory',
        ),
        migrations.AlterField(
            model_name='site2post',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], icon='arrow-right', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], icon='arrow-right', label='Right column content'))])), ('three_columns', wagtail.core.blocks.StructBlock([('column1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], icon='arrow-right', label='Column 1')), ('column2', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], icon='arrow-right', label='Column 2')), ('column3', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], icon='arrow-right', label='Column 3'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], blank=True, null=True),
        ),
    ]
