# Generated by Django 3.0.6 on 2020-06-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('site2', '0013_site2categoryindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site2TagIndexPage',
        ),
    ]
