# Generated by Django 3.0.6 on 2020-06-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0018_site2newpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site2newpost',
            old_name='text',
            new_name='body',
        ),
    ]
