# Generated by Django 3.0.6 on 2020-06-10 20:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0019_auto_20200610_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site2newpost',
            name='body',
            field=wagtail.core.fields.StreamField([('exe_htmljs', wagtail.core.blocks.TextBlock())], blank=True, null=True),
        ),
    ]
