# Generated by Django 3.0.6 on 2020-06-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0021_formpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='tags',
        ),
    ]
