# Generated by Django 3.0.6 on 2020-06-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('site2', '0022_auto_20200610_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
