# Generated by Django 3.0.6 on 2020-08-19 18:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0024_auto_20200819_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site2post',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock()), ('code_django', wagtail.core.blocks.StructBlock([('views', wagtail.core.blocks.TextBlock()), ('template', wagtail.core.blocks.TextBlock()), ('urls', wagtail.core.blocks.TextBlock())]))], icon='arrow-right', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock()), ('code_django', wagtail.core.blocks.StructBlock([('views', wagtail.core.blocks.TextBlock()), ('template', wagtail.core.blocks.TextBlock()), ('urls', wagtail.core.blocks.TextBlock())]))], icon='arrow-right', label='Right column content'))])), ('three_columns', wagtail.core.blocks.StructBlock([('column1', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock()), ('code_django', wagtail.core.blocks.StructBlock([('views', wagtail.core.blocks.TextBlock()), ('template', wagtail.core.blocks.TextBlock()), ('urls', wagtail.core.blocks.TextBlock())]))], icon='arrow-right', label='Column 1')), ('column2', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock()), ('code_django', wagtail.core.blocks.StructBlock([('views', wagtail.core.blocks.TextBlock()), ('template', wagtail.core.blocks.TextBlock()), ('urls', wagtail.core.blocks.TextBlock())]))], icon='arrow-right', label='Column 2')), ('column3', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock()), ('code_django', wagtail.core.blocks.StructBlock([('views', wagtail.core.blocks.TextBlock()), ('template', wagtail.core.blocks.TextBlock()), ('urls', wagtail.core.blocks.TextBlock())]))], icon='arrow-right', label='Column 3'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('exe_htmljs', wagtail.core.blocks.TextBlock()), ('code_bash', wagtail.core.blocks.TextBlock()), ('code_py', wagtail.core.blocks.TextBlock()), ('code_htmljs', wagtail.core.blocks.TextBlock())], blank=True, null=True),
        ),
    ]
